services:
  redis:
    container_name: redis
    image: redis:alpine3.19
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - redis-net
  app:
    container_name: app
    build:
      context: ./docker/app
    volumes:
      - ./app:/var/www/app
    depends_on:
      - redis
    networks:
      - redis-net
      - nginx
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - redis
    networks:
      - nginx
networks:
  redis-net:
  nginx:
volumes:
  redis-data:
